email_domain: "go-api-dev.beaugmented.ai"
from_email_name: Go API
from_email_address: test@beaugmented.ai
skipjwt: '{"get": "\/(health|config|version|anon|$)", "post": "\/(login|register|forgot_password|reset_password|anon)", "patch": "\/(anon)", "delete": "\/(anon)"}'
